# Generated by Django 5.2 on 2025-04-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_client_code_remove_user_id_user_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_code', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('insurance_type', models.CharField(choices=[('home', 'home'), ('health', 'health'), ('auto', 'auto'), ('life', 'life')], max_length=100)),
                ('suscription_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
    ]
